version: '3.8'
services:
  api:
    build: .
    image: transparencia-pgd/api:latest
    mem_limit: 2g
    mem_reservation: 1g
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
    ports:
      - "8880:8880"

  frontend:
    build:
      context: ./front-end  # Substitua pelo caminho correto
      dockerfile: Dockerfile.prod
    image: transparencia-pgd/frontend:latest
    ports:
      - "8188:80"
      - "8843:443"
    depends_on:
      - api