version: '3.8'
services:
  api:
    build: .
    image: transparencia-pgd/api:latest
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
    ports:
      - "8880:8880"

  frontend:
    image: node:22.14.0-alpine
    working_dir: /app
    volumes:
      - ./front-end:/app  # Substitua pelo caminho do front-end
      - /app/node_modules  # Evita problemas com node_modules
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    ports:
      - "5173:5173"  # Porta padrão do Vite
    depends_on:
      - api
