version: '3.8'
services:
  petrvs-transparencia-api:
    build: .
    image: transparencia-pgd/api:latest
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
    ports:
      - "8880:8880"
