name: Build and Push Docker Image

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Versão"
        required: true
        default: "lastest"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: TransparenciaPGD

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Login no GitHub Container Registry (usando Credential Store)
        run: echo "${{ secrets.GHCR_BPD }}" | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin

      - name: Construir e enviar a imagem Docker
        run: |
          VERSION=${{ github.event.inputs.version }}
          echo "Imagem = ghcr.io/${{ github.repository }}:$VERSION"
          IMAGE_NAME=ghcr.io/${{ github.repository }}:$VERSION
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME

      - name: Logout do Docker
        run: docker logout ghcr.io
